name: Deploy App

on:
  push:
    branches:
      - master  # Trigger deploy when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add server's SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts


      - name: Upload files via SCP
        run: |
          # Explicitly enable password authentication for SCP
          export SSHPASS="${{ secrets.SERVER_PASSWORD }}"
          sshpass -e scp -r ./ user@${{ secrets.SERVER_IP }}:/var/www/elfino/cubic-cube/

      # SSH into your server to build and run the Docker container
      - name: Build and Deploy on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/elfino/cubic-cube/
            docker build -t cubic-cube .
            docker stop cubic-cube || true
            docker rm cubic-cube || true
            docker run --env-file .env -p 3500:3500 cubic-cube #todo - create env on the fly with secrets.
